sudo: required
services:
  - docker

before_install:
  - docker build -t andrewvicencio/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run andrewvicencio/react-test npm test -- --coverage

after_success:
  - docker build -t andrewvicencio/multi-client ./client
  - docker build -t andrewvicencio/multi-nginx ./nginx
  - docker build -t andrewvicencio/multi-server ./server
  - docker build -t andrewvicencio/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push andrewvicencio/multi-client
  - docker push andrewvicencio/multi-nginx
  - docker push andrewvicencio/multi-server
  - docker push andrewvicencio/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: arn:aws:s3:::elasticbeanstalk-us-east-1-137737848787
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY